### ISSUE TITLE
Convert - step 4 "Copy"

### ISSUE THREAD

**Issue by Oleciniya** [apay-io/apay-io#105]
Change button "Copy" on standard icon copy
<img width="854" alt="Снимок экрана 2020-03-23 в 14 29 37" src="https://user-images.githubusercontent.com/31649969/77292452-e52d1f80-6d12-11ea-9119-678d2531385a.png">

**Comment by s-a-y** [comment]
Mostly done, one more thing - let's add another copy button next to the amount
32.456456 XLM [Copy]
and it should copy only number into the clipboard

Can be useful sometimes for non trivial amounts
