### ISSUE TITLE
Not able to contribute funds

### ISSUE THREAD

**Issue by BouweCeunen** [apay-io/apay-io#192]
Hi, I've got USD available but it says that I only have a max of 0?

![image](https://user-images.githubusercontent.com/5576686/82756354-0b863e80-9dda-11ea-9010-48a2a1a76022.png)

**Comment by s-a-y** [comment]
Hey,
are you sure you have USDT issued by apay.io? Anchor USD or others won't work.
It's probably faster to continue this conversation in email via support@apay.io or on [telegram](https://t.me/umbre1)

**Comment by BouweCeunen** [comment]
Didn't use USDT issued by apay.io. My bad! It could be useful to include a message maybe for future users.
