### ISSUE TITLE
 Convert - 2 step

### ISSUE THREAD

**Issue by Oleciniya** [apay-io/apay-io#89]
Button does not work "Next step" when entering a real bitcoin address
<img width="887" alt="Снимок экрана 2020-03-12 в 11 33 56" src="https://user-images.githubusercontent.com/31649969/76487657-a87d4080-6455-11ea-88c5-2ccabb005b68.png">

**Comment by s-a-y** [comment]
@MazilaNx also note the position of "tick" icon under (1)
